In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
import pickle
import tensorflow as tf

In [3]:
from tensorflow.keras.models import load_model
model=load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [5]:



with open( 'lable_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo=pickle.load(file)

with open('scaler.pickle','rb') as file:
    scaler=pickle.load(file)

In [6]:
input_data={

    'CreditScore':600,
    'Geography':'France',	
    'Gender':'Male',
    'Age':  40,
    'Tenure': 3,	
    'Balance': 600000,	
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000	
}

In [7]:
geo_encoded=onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

s:\Deep_Learning\ANN_Project\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [8]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [10]:
input_data=pd.DataFrame([input_data])

In [11]:
input_data=pd.concat([input_data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [12]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,600000,2,1,1,50000,1.0,0.0,0.0

In [13]:
input_data['Gender']=label_encoder_gender.transform(input_data['Gender'])

In [15]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,600000,2,1,1,50000,1.0,0.0,0.0

In [16]:
scaled_data=scaler.transform(input_data)

In [17]:
prediction=model.predict(scaled_data)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

array([[0.9222405]], dtype=float32)

In [18]:
prediction_prb=prediction[0][0]
prediction_prb

0.9222405

In [19]:
if prediction_prb > 0.5:
    print("The customer is likely to churn")
else:
    print("The customer is not likely to churn")

The customer is likely to churn